### ISSUE TITLE
Weird overlay in Steam Settings -> Interface panel.

### ISSUE THREAD

**Issue by Lynxaa** [DirtDiglett/Pressure-for-Steam#199] opened 2015-02-16 15:50 UTC
http://i.imgur.com/zafz0NB.png
I am using the latest release.

**Comment by Zerathos** [comment] 2015-02-16 15:59
See #181.

**Comment by DirtDiglett** [comment] 2015-02-17 03:54
Duplicate of #181, closing.

**Closed by DirtDiglett** 2015-02-17 03:54 UTC
Labels: duplicate
