### ISSUE TITLE
Friends buttons drop below container

### ISSUE THREAD

**Issue by Lynxaa** [DirtDiglett/Pressure-for-Steam#201] opened 2015-02-16 16:03 UTC
http://i.imgur.com/nkgDApv.png
http://i.imgur.com/1zgw4bv.png
http://i.imgur.com/Lp5hvmc.png
http://i.imgur.com/VTxZN3e.png

**Comment by GOGO98901** [comment] 2015-02-16 16:14
Duplicate of #198

**Comment by DirtDiglett** [comment] 2015-02-17 01:49
Fixed this up.

**Closed by DirtDiglett** 2015-02-17 01:49 UTC
