### ISSUE TITLE
Some text not using custom font

### ISSUE THREAD

**Issue by LordFatBastard** [DirtDiglett/Pressure-for-Steam#236] opened 2015-03-27 15:36 UTC
Some files don't use the custom font in seeming random parts of steam, the attached screenshot is an example.

![](http://i.imgur.com/nlnOhc3.png)

**Comment by DirtDiglett** [comment] 2015-03-28 04:13
If you're referring to the headings of news items they are not meant to be using the same font as "RECENT NEWS". This is by design. Not an issue. Closing.

**Closed by DirtDiglett** 2015-03-28 04:13 UTC
