### ISSUE TITLE
Fix's and Suggestions 

### ISSUE THREAD

**Issue by Wiggin38** [DirtDiglett/Pressure-for-Steam#188] opened 2015-02-07 21:12 UTC
Some fixs and sugestions!
Anyway this:

<a href="http://imgur.com/gSgFfBG"><img src="http://i.imgur.com/gSgFfBG.jpg" title="source: imgur.com" /></a>

Can look like this ?

<a href="http://imgur.com/PMhIFdp"><img src="http://i.imgur.com/PMhIFdp.jpg" title="source: imgur.com" /></a>

I realize the issue with my username is because of the "flower" charcter but still would like a fix. 

If someone wish's to inform me how to make these changes myself, I am sure I can make them myself. 

Really enjoying this skin!

**Comment by Js41637** [comment] 2015-02-08 02:00
Umm is possible, I can quickly try and edit it.

Gotta go to work but was able to make it so it's aligned to the left however the music library page is still a little broken.

Updated file, goes in `Steam\skins\Pressure-for-Steam\resource\layout`
Just open it and then save the file as uinavigatorpanel.layout
http://puu.sh/fCsEZ/a8d54c1682.layout

if you want to edit it yourself add this code to where it is in the file;
I think this is it, probably easier to just use the file I provided above.
```
		place [!$OSX] { 
			control="library_search" 
			margin-right=194 
			dir=right 
			height=25
			start=library_filters
			x=40
		}


		place [$OSX] { 
			control="library_search" 
			margin-right=194 
			dir=right 
			height=25
			start=library_filters
			x=40
		}

		place {
			control="library_filters"
			dir=right
			margin-right=200
			height=25
			width=160
			start=label_zoom_separator
			x=35
		}
```

**Comment by Wiggin38** [comment] 2015-02-08 05:11
Awesome! Thank you very much. Not to be a bother but any way to move my name in line with Community and library? 

Again Thanks!

**Comment by Js41637** [comment] 2015-02-08 06:36
It should already be in line, are you using special characters or something?

**Comment by Wiggin38** [comment] 2015-02-08 06:37
Yes I am. Is there a way to allow it to be in line while using a special character ?

**Comment by Js41637** [comment] 2015-02-08 06:54
I am not a Skinning Expert but I don't imagine this can be fixed with the styles steam supports.

**Comment by Wiggin38** [comment] 2015-02-08 06:54
Alright, well thank you for your help none the less! Very much appreciated.

**Comment by DirtDiglett** [comment] 2015-02-09 01:14
The issue is that some special characters go below the baseline for the font, which in Steam's eyes pushes the baseline lower. The positioning here is on that baseline so it forces the text higher.

No, there's no reasonable way to fix this to have it display like those of us with normal names and no silly unicode characters.

**Closed by DirtDiglett** 2015-02-09 01:14 UTC

**Comment by Wiggin38** [comment] 2015-02-09 01:50
Any way to change the font then ? Different fonts seem to make it less obvious. It is a normal name, no reason to make digs at someones name.

**Comment by Js41637** [comment] 2015-02-09 01:57
You can change the font by editing `settings.styles` in the `includes` folder if you wish.

**Comment by Wiggin38** [comment] 2015-02-09 03:00
Thank you Js41637. I found a font that looks much better. Your help was much appreciated.
