### ISSUE TITLE
Download page bar

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#379] opened 2015-06-19 11:53 UTC
The download bar does not will width of window when snapped to my screen(1336x768)
But when window resided to be smaller the bar fills width.
The two states are shown bellow
![download](https://cloud.githubusercontent.com/assets/2751799/8252921/1fbc44ec-1682-11e5-9ba3-2aab6257e9a0.png)

**Comment by Js41637** [comment] 2015-06-20 05:46
So does it always do this when you resize? I can't reproduce this.

**Comment by GOGO98901** [comment] 2015-06-20 09:13
Yes this happens every time. I'm running latest beta and uninstalled the skin and re installed it and the same happened.

**Comment by DirtDiglett** [comment] 2015-06-29 12:26
Unfortunately this can't be fixed in Pressure. It's an issue that occurs across every skin so not specific to mine. It's due to the way the bars are calculated, they're done in 'blocks' and it seems that the default skin is cheeky and just fades it out instead of letting it abruptly stop. I may mimic this down the line.

See here with Pressure, Air, and Metro:
![dlpage](https://cloud.githubusercontent.com/assets/3527401/8407823/d63f44b6-1ead-11e5-8a4b-55def55eaaf7.png)

**Closed by DirtDiglett** 2015-06-29 12:26 UTC
