### ISSUE TITLE
Missing Fonts and Colors

### ISSUE THREAD

**Issue by kloutier** [DirtDiglett/Pressure-for-Steam#408] opened 2015-08-08 19:45 UTC
When you have parental mode enable the text is the same color as the bar. If you log out of it the colors and fonts appear.

**Comment by bykidi** [comment] 2015-08-09 03:39
ehmm... screenshots, perhabs?
![default](https://cloud.githubusercontent.com/assets/1337953/9153473/487a8e3c-3e61-11e5-9431-daa0a7f6b796.PNG)
![2](https://cloud.githubusercontent.com/assets/1337953/9153474/48811324-3e61-11e5-85f5-45caeb20094d.PNG)

**Comment by kloutier** [comment] 2015-08-10 22:34
<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/9141400/9185922/711afe36-3f7d-11e5-8779-c80867aa13c2.PNG">

<img width="960" alt="capture2" src="https://cloud.githubusercontent.com/assets/9141400/9185947/a53bb142-3f7d-11e5-98ce-3332381605c2.PNG">

**Comment by Js41637** [comment] 2015-08-11 03:00
I'd imagine it's because they're disabled? Are they disabled? Are you saying the colours should be changed when they're disabled or are they not disabled and is a bug?

**Comment by bykidi** [comment] 2015-08-11 05:20
You getting this because you disable everything in Family Sharing Settings

**Comment by bykidi** [comment] 2015-08-15 08:58
The stranger one is that 'zero' new notifications number moving itself by some reason

![default](https://cloud.githubusercontent.com/assets/1337953/9288232/e3e0c6a6-4344-11e5-9cad-94a7b65e6546.PNG)
![2](https://cloud.githubusercontent.com/assets/1337953/9288233/e3e77b36-4344-11e5-86cd-3f41281e0e22.PNG)

**Comment by DirtDiglett** [comment] 2015-08-17 01:52
With Family Mode on it can disabled certain features like community features and such, so if they are disabled they reflect this with their font style, in this case being disabled leaves the words dark to indicate it.

This is expected behaviour.

**Closed by DirtDiglett** 2015-08-17 01:52 UTC
