### ISSUE TITLE
Top-right avatar not refreshing

### ISSUE THREAD

**Issue by rojona** [DirtDiglett/Pressure-for-Steam#409] opened 2015-08-18 13:19 UTC
The personal avatar in the top right of the skin doesn't refresh when you change the avatar. I've changed mine three days ago and logged in and out of Steam many times and changed back and forth between the default skin and Pressure to no avail. It still shows the same avatar i used when i installed Pressure.

Until this is fixed, is there another way for me to refresh this picture?

**Comment by J5lx** [comment] 2015-08-19 14:09
I recently had a similar issue when I changed the icon of a non-Steam game. Because Steam cached a resized version of the icon at /tmp it didn't change until I deleted the cached version. Maybe that's also the cause for this issue. Have you tried rebooting your system? (This should flush the cache completely)

**Comment by DirtDiglett** [comment] 2015-08-25 10:39
This isn't a skin-specific or skin-caused issue. This is an issue with your steam install/PC, as you said yourself changing to default isn't fixing it.

Closing.

**Closed by DirtDiglett** 2015-08-25 10:39 UTC
