### ISSUE TITLE
Shared game text issue "Shared by: Library is........"

### ISSUE THREAD

**Issue by Jorchking** [DirtDiglett/Pressure-for-Steam#174] opened 2015-02-04 05:29 UTC
![pressure_issue_1](https://cloud.githubusercontent.com/assets/8688412/6035599/6c5902c2-ac15-11e4-9159-6106e04a00d8.png)

Is in general, not about other languages.

Where is the date, shared by option is cut (next to Buy/play button).

**Comment by Zerathos** [comment] 2015-02-04 05:35
Duplicate of #126...probably, anyway. Yours cuts off in a different place, but that's likely because the different language setting makes things a different length.

**Comment by Jorchking** [comment] 2015-02-04 05:39
@Zerathos Yes, but is different, this is cut off by the sides not at the bottom.
Anyway, I tried in english and is cut too
![pressure_issue_2](https://cloud.githubusercontent.com/assets/8688412/6035729/0db8de7a-ac17-11e4-96c0-80b37c849248.png)

**Comment by Zerathos** [comment] 2015-02-04 05:44
Yeah, the bottom was what happened at first, but if you read a little further down there was a fix for that that then caused it to cut off the sides, like you see there.

**Comment by DirtDiglett** [comment] 2015-02-17 05:44
Should be 100% fixed :+1:

**Closed by DirtDiglett** 2015-02-17 05:44 UTC
