### ISSUE TITLE
Phone reminder message bug (see screenshots)

### ISSUE THREAD

**Issue by iElCapitan** [DirtDiglett/Pressure-for-Steam#419] opened 2015-09-16 15:37 UTC
First of all sorry for just providing the screenshots without more informations (I can add them later if needed), but I'm in a hurry^^

So here are the screenshots of the bug:

![bug_1](https://cloud.githubusercontent.com/assets/13371024/9909697/93fb0476-5c99-11e5-8e08-c505186da0c6.jpg)
![bug_2](https://cloud.githubusercontent.com/assets/13371024/9909703/99d3fe0c-5c99-11e5-90f4-73174cae534e.jpg)

**Comment by Brottweiler** [comment] 2015-09-16 15:43
Can confirm, went here to report it if it wasn't already. :stuck_out_tongue:

**Comment by GOGO98901** [comment] 2015-09-16 16:43
see #415

**Comment by iElCapitan** [comment] 2015-09-16 16:51
@GOGO98901 I'm not sure but I think my issue is not the same as in #415.
#415 is about the phone bar covering up the email bar, my issue is something else i think...

**Comment by Js41637** [comment] 2015-09-17 02:45
This is a duplicate of issue #417.

**Comment by DirtDiglett** [comment] 2015-09-17 11:07
Fixed in the latest commits.

**Closed by DirtDiglett** 2015-09-17 11:07 UTC
