### ISSUE TITLE
[Ubuntu 14.04.1 LTS] Bottom part of text "cut" on message window

### ISSUE THREAD

**Issue by unleashy** [DirtDiglett/Pressure-for-Steam#116] opened 2014-11-21 19:58 UTC
Here is a more descriptive image:

![scr-cap](https://cloud.githubusercontent.com/assets/6519366/5148630/f9754ba0-71a7-11e4-88bd-5ed646be2b06.png)

Do you see the slight "cut" into the letters "tails"? That's what I'm talking about. Also, underlines (_) won't show up.

**Comment by s0r00t** [comment] 2015-02-15 18:24
Also happening here, Xubuntu 14.04. Seems to be a font problem.

**Comment by xnaas** [comment] 2015-03-23 22:48
Happening for me as well on the latest version of Arch Linux.

**Comment by DirtDiglett** [comment] 2015-03-26 01:36
I'm just going through a cleanup of the code for the project, after this (Should be done in a few days) I am going to try an experimental fix for this, but in order to do so I must know: Does the text cutoff issue occur on the default Steam skin?

**Comment by xnaas** [comment] 2015-03-26 02:12
Sorry for this shit quality of the image: http://a.pomf.se/jyjdmx.png But no. No cutoff on stock skin.

**Comment by DirtDiglett** [comment] 2015-03-27 04:41
@xnaas Can you try the latest commit for me, if Steam Default is working fine we'll try using the same base font (Arial in this case) to see if the issue is resolved.

Let me know.

**Comment by s0r00t** [comment] 2015-03-29 00:02
Right now it's fixed, but the font seems different for me o_o

**Comment by DirtDiglett** [comment] 2015-03-29 00:45
It is a different font, it's Arial which is what default Steam was using.

**Comment by DirtDiglett** [comment] 2015-03-30 03:56
Can someone send me a screenshot of how it's now looking on Steam for me please?

**Comment by xnaas** [comment] 2015-04-03 16:41
Hi. Sorry for the delayed response. I was actually using a *different* skin for Steam (so this text issue seems to be a problem for all Steam skins on Linux) and then was busy and never got around to changing my skin. Anyway, here's a screenshot using the latest version of Pressure: http://puu.sh/h0alK/f70d7b144a.png

**Closed** 2015-04-03 22:52 UTC
