### ISSUE TITLE
Steam overlay issue

### ISSUE THREAD

**Issue by Zet1** [DirtDiglett/Pressure-for-Steam#123] opened 2014-11-26 23:49 UTC
I've encountered an issue with the new steam overlay while playing game dev tycoon. The overlay doesn't fit the whole window, and looks incredibly small like this:
http://puu.sh/d6TYm.png

It looks the same in a fullscreen window, and on goat sim, the overlay works fine. I'll try to find out what other games might also have the same problem.

**Comment by DirtDiglett** [comment] 2015-01-06 11:48
So the issue isn't pressure specifically, it appears to be a bug with how the overlay determines screen resolution versus game resolution: http://www.reddit.com/r/Steam/comments/2rhgfq/steam_overlay_extremely_small_and_in_bottom_left/

closing as it isn't pressure

**Closed by DirtDiglett** 2015-01-06 11:48 UTC
Labels: More Information Required
